### ISSUE TITLE
Incorrect types

### ISSUE THREAD

**Issue by JasonDevTech** [digitalmio/next-api-zod#1]
https://github.com/digitalmio/next-api-zod/blob/35394c874b363006f1329b219dedee79baf927ba/src/index.ts#L55

For TypeScript users, this should be `void | Response | Promise<void | Response>` and not unknown. Alternatively, if we can pass generics to the return value that would be great too.

**Comment by digitalmio** [comment]
Good call. I'll change this asap (not that anyone is using this package by the looks of NPM stats). 
I'll think about generics when I'll have a bit of free time - hopefully this weekend.
